name: reload_on_save
description: Reload on save.
version: 0.0.1
author: algoshipda

executables:
  dart-reload-on-save: app

dependencies:
  watcher: ^0.9.7+15
  vm_service: ^4.2.0
  args: ^1.6.0
  path: ^1.7.0
